### ISSUE TITLE
20180417 회의록

### ISSUE THREAD

**Issue by jahyun-dev** [modumarl/proposal#5]
MultiAgent RL

## 문제 설정

- 협동 => chase
  - 쫒는 애들은 MARL
  - 도망치는 애들은 룰기반
- combat? 싸움 알고리즘?
  - 평가? 룰기반 vs MARL 에이전트

잡는게 더 쉽다
축구는 적합한 상황이 아님. 패스 정도...

## 학습

방법론

- centralized
- decentralized
- master-and-slave

## MARL 논문 작성 포인트

- MARL
  - 다수의 에이전트
  - 서로간의 통신, 상호작용
  - (+) 서로의 경험이 공유되면 좋다!
  - (+) 에이전트의 수가 변해도 잘되야 한다!
  - (+) 역할이 다른 에이전트를 하며 잘 커뮤니케이션 하는 것
- 보여주는 방법에 대한 고민

## Unity 

- 서바이벌 슈터?

## 최종 구현

좀비 게임?
에이전트의 롤을 다르게?

## TODO

- chase 환경 구현 
  - 시야를 추구하거나
- 논문 리뷰
  - 어떻게 정보를 잘 조합해 액션을 뽑을까?
  - 에이전트 간 커뮤니케이션
  - 커뮤니케이션 간 중요도를 파악할 수 있는 방법은 없을까?

**Comment by jahyun-dev** [comment]
논문 리뷰 공유를 위한 레포지토리를 생성했습니다.

https://github.com/modumarl/review-papers

따로 좋은 방법이 있다면 말씀주세요.

**Comment by jahyun-dev** [comment]
논문 리뷰 후보

- [ ] [Multi-Agent Actor-Critic for Mixed Cooperative-Competitive Environments](http://papers.nips.cc/paper/7217-multi-agent-actor-critic-for-mixed-cooperative-competitive-environments)
- [ ] [A multi-agent reinforcement learning model of common-pool resource appropriation](http://papers.nips.cc/paper/6955-a-multi-agent-reinforcement-learning-model-of-common-pool-resource-appropriation)
- [ ] [A Unified Game-Theoretic Approach to Multiagent Reinforcement Learning](http://papers.nips.cc/paper/7007-a-unified-game-theoretic-approach-to-multiagent-reinforcement-learning)
- [ ] [Dynamic Safe Interruptibility for Decentralized Multi-Agent Reinforcement Learning](https://infoscience.epfl.ch/record/229332/files/safe_ai.pdf)
- [ ] [Policy Gradient With Value Function Approximation For Collective Multiagent Planning](http://papers.nips.cc/paper/7019-policy-gradient-with-value-function-approximation-for-collective-multiagent-planning)
- [ ] [Emergence of Language with Multi-agent Games: Learning to Communicate with Sequences of Symbols](http://papers.nips.cc/paper/6810-emergence-of-language-with-multi-agent-games-learning-to-communicate-with-sequences-of-symbols)
- [ ] [Cooperative Multi-Agent Control Using Deep Reinforcement Learning](http://ala2017.it.nuigalway.ie/papers/ALA2017_Gupta.pdf)
- [ ] [Learning to Communicate with Deep Multi-Agent Reinforcement Learning](https://arxiv.org/abs/1605.06676)
- [ ] [Lenient Multi-Agent Deep Reinforcement Learning](https://arxiv.org/abs/1707.04402)
- [ ] [Modeling Others using Oneself in Multi-Agent Reinforcement Learning](https://arxiv.org/abs/1802.09640)
- [ ] [Multi-Agent Deep Reinforcement Learning](http://cs231n.stanford.edu/reports/2016/pdfs/122_Report.pdf)
- [ ] [Multi-agent Reinforcement Learning in Sequential Social Dilemmas
](http://cs231n.stanford.edu/reports/2016/pdfs/122_Report.pdf)
- [ ] [Revisiting the Master-Slave Architecture in Multi-Agent Deep Reinforcement Learning
](https://arxiv.org/abs/1712.07305)
