### ISSUE TITLE
20180424 회의록

### ISSUE THREAD

**Issue by jahyun-dev** [modumarl/proposal#7]
# TODO

- 매주 화, 금요일 모임
- 금요일은 멘토님과 모임
- 기초 스터디와 논문 준비를 같이 진행. 기초에 중점

## 기초 스터디

~ 5월 15일

- [ ] 강의  노트 처음부터 훑기
  - 강의 자료를 처음부터 공부하고, 정리해 발표한다.
  - [ ] DP & Q-Learning (송경)
  - [ ] CNN and DQN (구자현)
  - [ ] Policy Gradient (허재영)

## 논문 준비

기초랑 같이 진행하기로

- [x] 유니티 그리드 월드 pursuit 환경 구현
- [ ] 알고리즘 구현 / 비교
  - [ ] DQN
  - [ ] MADDPG
  - ... ?
- [ ]  논문 리뷰
  - [ ]  Multi-Agent Actor-Critic for Mixed Cooperative-COmpetitive Environment
  - [ ] Proximal Policy Optimization Algorithms

## 1차 중간점검

- ?... 뭘 해야하지...? :(
- 패쓰합시다...
